services:
  db:
    image: postgres:16
    container_name: financeiro_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: financeiro_user
      POSTGRES_PASSWORD: financeiro_pass
      POSTGRES_DB: financeiro_dev
    ports:
      - "5432:5432"
    volumes:
      - financeiro_pgdata:/var/lib/postgresql/data

  pgadmin:
   image: dpage/pgadmin4
   environment:
     PGADMIN_DEFAULT_EMAIL: viniciustei@admin.com.br
     PGADMIN_DEFAULT_PASSWORD: admin_123
   ports:
     - "5433:80"
   depends_on:
     - db

volumes:
  financeiro_pgdata:
