import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("health", "routes/health.ts"),
  route("setup", "routes/setup.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("join/:token", "routes/join.$token.tsx"),
  layout("routes/_app.tsx", [
    route("api/households/options", "routes/households.options.ts"),
    route("api/households/active", "routes/households.active.ts"),
    route("households/:householdId/manage", "routes/households.$householdId.manage.tsx"),
    route("households/:householdId/invite", "routes/households.$householdId.invite.tsx"),
    route("households/:householdId/categories", "routes/households.$householdId.categories.tsx"),
    route("households/:householdId/transactions", "routes/households.$householdId.transactions.tsx"),
    route("households/:householdId", "routes/households.$householdId.tsx"),
    route("households", "routes/households.tsx"),
    route("invite", "routes/invite.tsx"),
    route("settings", "routes/settings.tsx"),
    route("settings/change-password", "routes/settings.change-password.tsx"),
    route("settings/delete", "routes/settings.delete.tsx"),
    route("accounts", "routes/accounts.tsx"),
    route("cards", "routes/cards.tsx"),
    route("card/:creditCardId", "routes/card.$creditCardId.tsx"),
    route("transactions", "routes/transactions.tsx"),
    route("transactions/receipt", "routes/transactions.receipt.tsx"),
    route("categories", "routes/categories.tsx"),
    index("routes/home.tsx"),
  ]),
] satisfies RouteConfig;
